version: "3.8"
services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "db"
      MYSQL_USER: "docker"
      MYSQL_PASSWORD: "docker"
    ports:
      - "3306:3306"
